language: node_js
node_js:
  - "10"
cache: npm
branches:
  only:
    - "master"
env:
  - NODE_ENV="development"
before_script:
  - git remote set-url origin https://katrotz:${GITHUB_TOKEN}@github.com/katrotz/atlas.git
  - npm run bootstrap
script: npm version patch && npm publish --access public && git push --tags
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
