language: node_js
node_js:
  - "10"
cache: npm
branches:
  only:
    - "master"
env:
  global:
    - NODE_ENV="development"
before_script:
  - npm run ci:setup
  - npm run bootstrap
script: PUBLISH_BRANCH_NAME="$([ -n $TRAVIS_PULL_REQUEST_BRANCH ] && echo $TRAVIS_PULL_REQUEST_BRANCH || echo $TRAVIS_BRANCH)" ./scripts/release/publish.sh
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
