language: node_js
node_js:
  - "10"
cache: npm
branches:
  only:
    - "master"
env:
  - NODE_ENV="development"
before_script:
  - npm run ci:setup
  - npm run bootstrap
script: ./scripts/release/publish.sh
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
