language: node_js
node_js:
  - "10"
cache: npm
branches:
  only:
    - "master"
env:
  - NODE_ENV="development"
after_success:
  - git remote set-url origin https://katrotz:${GITHUB_TOKEN}@github.com/katrotz/atlas.git
  - npm publish
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true

