---

- name: define common bash aliases
  blockinfile:
    dest: "/home/{{ provision_user_name }}/.bash_aliases"
    block: |
      # Makes all of the other aliases function correctly when used with sudo
      alias sudo='sudo '

      # Prints disk usage in human readable form
      alias d="du -sh"

      # Clear the screen of your clutter
      alias c="clear"
      alias cl="clear;ls;pwd"

      # GREP Motifications
      alias grep="grep --color"
      alias grepp="grep -P --color"

      # Json tools (pipe unformatted to these to nicely format the JSON)
      alias json="python -m json.tool"
      alias jsonf="python -m json.tool"

      # Friendly listing
      alias ls='ls -AlhF --color=auto'

      # Displays disk usage
      alias usage="du -cBM -d1 2> >(grep -v 'Permission denied') | sort -n"
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    insertafter: EOF
    create: yes
    owner: "{{ provision_user_name }}"
    group: "{{ provision_user_group }}"

- name: register bash aliases
  blockinfile:
    dest: "/home/{{ provision_user_name }}/.bashrc"
    block: |
      if [ -f ~/.bash_aliases ]; then
          . ~/.bash_aliases
      fi
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    insertafter: EOF
    create: yes
    owner: "{{ provision_user_name }}"
    group: "{{ provision_user_group }}"
